# Generated by Django 2.2.6 on 2019-10-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='notes.Note'),
        ),
    ]
